export const ingredients = [
  // Vegetables
  { label: 'Tomato', value: 'pomodoro' },
  { label: 'Cherry Tomato', value: 'pomodorini' },
  { label: 'San Marzano Tomato', value: 'pomodoro_san_marzano' },
  { label: 'Garlic', value: 'aglio' },
  { label: 'Onion', value: 'cipolla' },
  { label: 'Red Onion', value: 'cipolla_rossa' },
  { label: 'Shallot', value: 'scalogno' },
  { label: 'Carrot', value: 'carota' },
  { label: 'Celery', value: 'sedano' },
  { label: 'Eggplant', value: 'melanzana' },
  { label: 'Zucchini', value: 'zucchina' },
  { label: 'Bell Pepper', value: 'peperone' },
  { label: 'Artichoke', value: 'carciofo' },
  { label: 'Radicchio', value: 'radicchio' },
  { label: 'Fennel', value: 'finocchio' },
  { label: 'Mushroom', value: 'funghi' },
  { label: 'Porcini Mushroom', value: 'porcini' },
  { label: 'Potato', value: 'patata' },
  { label: 'Arugula', value: 'rucola' },
  { label: 'Spinach', value: 'spinaci' },

  // Herbs & Aromatics
  { label: 'Basil', value: 'basilico' },
  { label: 'Parsley', value: 'prezzemolo' },
  { label: 'Rosemary', value: 'rosmarino' },
  { label: 'Thyme', value: 'timo' },
  { label: 'Sage', value: 'salvia' },
  { label: 'Oregano', value: 'origano' },
  { label: 'Mint', value: 'menta' },
  { label: 'Bay Leaf', value: 'alloro' },
  { label: 'Marjoram', value: 'maggiorana' },

  // Fruits
  { label: 'Lemon', value: 'limone' },
  { label: 'Orange', value: 'arancia' },
  { label: 'Fig', value: 'fico' },
  { label: 'Grape', value: 'uva' },
  { label: 'Peach', value: 'pesca' },
  { label: 'Pear', value: 'pera' },
  { label: 'Strawberry', value: 'fragola' },

  // Dairy & Eggs
  { label: 'Butter', value: 'burro' },
  { label: 'Egg', value: 'uovo' },
  { label: 'Milk', value: 'latte' },
  { label: 'Heavy Cream', value: 'panna' },
  { label: 'Mascarpone', value: 'mascarpone' },
  { label: 'Ricotta', value: 'ricotta' },

  // Cheeses
  { label: 'Parmigiano Reggiano', value: 'parmigiano_reggiano' },
  { label: 'Grana Padano', value: 'grana_padano' },
  { label: 'Pecorino Romano', value: 'pecorino_romano' },
  { label: 'Pecorino Toscano', value: 'pecorino_toscano' },
  { label: 'Mozzarella', value: 'mozzarella' },
  { label: 'Buffalo Mozzarella', value: 'mozzarella_di_bufala' },
  { label: 'Burrata', value: 'burrata' },
  { label: 'Gorgonzola', value: 'gorgonzola' },
  { label: 'Fontina', value: 'fontina' },
  { label: 'Taleggio', value: 'taleggio' },
  { label: 'Asiago', value: 'asiago' },
  { label: 'Provolone', value: 'provolone' },

  // Meats
  { label: 'Prosciutto', value: 'prosciutto' },
  { label: 'Prosciutto di Parma', value: 'prosciutto_di_parma' },
  { label: 'Pancetta', value: 'pancetta' },
  { label: 'Guanciale', value: 'guanciale' },
  { label: 'Salami', value: 'salame' },
  { label: 'Beef', value: 'manzo' },
  { label: 'Ground Beef', value: 'macinato_di_manzo' },
  { label: 'Veal', value: 'vitello' },
  { label: 'Chicken', value: 'pollo' },
  { label: 'Pork', value: 'maiale' },
  { label: 'Lamb', value: 'agnello' },
  { label: 'Italian Sausage', value: 'salsiccia' },
  { label: 'Mortadella', value: 'mortadella' },
  { label: 'Bresaola', value: 'bresaola' },

  // Seafood
  { label: 'Anchovy', value: 'acciuga' },
  { label: 'Squid', value: 'calamaro' },
  { label: 'Shrimp', value: 'gambero' },
  { label: 'Clam', value: 'vongola' },
  { label: 'Mussel', value: 'cozza' },
  { label: 'Sea Bass', value: 'branzino' },
  { label: 'Tuna', value: 'tonno' },
  { label: 'Octopus', value: 'polpo' },
  { label: 'Swordfish', value: 'pesce_spada' },

  // Grains & Pasta
  { label: 'Arborio Rice', value: 'riso_arborio' },
  { label: 'Carnaroli Rice', value: 'riso_carnaroli' },
  { label: 'Spaghetti', value: 'spaghetti' },
  { label: 'Penne', value: 'penne' },
  { label: 'Linguine', value: 'linguine' },
  { label: 'Tagliatelle', value: 'tagliatelle' },
  { label: 'Fettuccine', value: 'fettuccine' },
  { label: 'Lasagna', value: 'lasagna' },
  { label: 'Rigatoni', value: 'rigatoni' },
  { label: 'Orecchiette', value: 'orecchiette' },
  { label: 'Semolina Flour', value: 'semola' },
  { label: '00 Flour', value: 'farina_00' },
  { label: 'Polenta', value: 'polenta' },

  // Oils, Vinegars & Condiments
  { label: 'Olive Oil', value: 'olio_d_oliva' },
  { label: 'Extra Virgin Olive Oil', value: 'olio_extravergine_d_oliva' },
  { label: 'Balsamic Vinegar', value: 'aceto_balsamico' },
  { label: 'Red Wine Vinegar', value: 'aceto_di_vino_rosso' },
  { label: 'White Wine Vinegar', value: 'aceto_di_vino_bianco' },
  { label: 'Capers', value: 'capperi' },
  { label: 'Black Olives', value: 'olive_nere' },
  { label: 'Green Olives', value: 'olive_verdi' },
  { label: 'Sun-dried Tomatoes', value: 'pomodori_secchi' },
  { label: 'Pine Nuts', value: 'pinoli' },
  { label: 'Walnuts', value: 'noci' },
  { label: 'Hazelnuts', value: 'nocciole' },

  // Other
  { label: 'White Wine', value: 'vino_bianco' },
  { label: 'Red Wine', value: 'vino_rosso' },
  { label: 'Tomato Paste', value: 'concentrato_di_pomodoro' },
  { label: 'Tomato Sauce', value: 'passata_di_pomodoro' },
];
