import type { Metadata } from 'next';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import './globals.css';
import { Roboto } from 'next/font/google';
import theme from '../theme';
import { ThemeProvider } from '@mui/material';
import {ClerkProvider, SignedIn, SignedOut, SignIn, UserButton} from "@clerk/nextjs";
import styles from "@/app/page.module.css";

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider>
    <html lang="en">
      <body className={roboto.variable}>
      <header className={styles.header}>
        <UserButton showName />
      </header>
        <AppRouterCacheProvider>
          <SignedOut>
            <SignIn routing="hash" />
          </SignedOut>
          <SignedIn >
          <ThemeProvider theme={theme}>{children}</ThemeProvider>
          </SignedIn>
        </AppRouterCacheProvider>
      </body>
    </html>
      </ClerkProvider>
  );
}
