import type {Metadata} from 'next';
import {AppRouterCacheProvider} from '@mui/material-nextjs/v15-appRouter';
import './globals.css';
import {Roboto} from 'next/font/google';
import theme from '../theme';
import {ThemeProvider} from '@mui/material';
import {ClerkProvider, SignedIn, SignedOut, SignIn, UserButton} from "@clerk/nextjs";


const roboto = Roboto({
    weight: ['300', '400', '500', '700'],
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-roboto',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        // wraps the container into a clerk auth session
        <ClerkProvider>
            <html lang="en">
            <body className={roboto.variable}>
            <header>
                {/*user profile page link and badge icon*/}
                <UserButton showName/>
            </header>
            <AppRouterCacheProvider>
                {/*when logged out, anything in the <SignedOut> container is hidden from the user.*/}
                <SignedOut>
                    {/*The only thing shown to the user is the sign in screen. @Marco please fix this css, it looks so bad.*/}
                    <SignIn routing="hash"/>
                </SignedOut>
                {/*Anything in the container below will be shown exclusively to signed-in users.*/}
                <SignedIn>
                    <ThemeProvider theme={theme}>{children}</ThemeProvider>
                </SignedIn>
            </AppRouterCacheProvider>
            </body>
            </html>
        </ClerkProvider>
    );
}
